version: '3.8'

services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@test2_tp?TNS_ADMIN=/app/oracle_wallet/
      - spring.datasource.username=java_ms_facturas_vet
      - spring.datasource.password=JavaMS1vetFAC
      - spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
    restart: always